### ISSUE TITLE
How do I use this file? I know nothing about git or python.

### ISSUE THREAD

**Issue by Kegs2477** [pnzrdrgoon/dndspellbook#1]
How do I use this file? I am a complete beginner, know nothing about git or python, but need Stephen's card generator. Sorry if this is the wrong place to ask. Didn't know how else to do it.

**Comment by agearhart** [comment]
Hey @Kegs2477 ,
With this Dockerfile you don't need to know either.  To use this first install Docker on your machine:
https://www.docker.com/products/docker-desktop

Once installed you can use the Dockerfile to to generate the PDF for you by running the command:
docker run -it -v c:/temp:/opt/output pnzrdrgoon/dndspelldeck:latest

Once complete you should be able to find the PDF generated at C:\Temp
Good question though and I'll update the ReadMe with this information.  I'll keep this issue open for you to reply with either your success or if you'd like more help.  More information on how to run the Dockerfile can be found at https://hub.docker.com/r/pnzrdrgoon/dndspelldeck/

**Comment by agearhart** [comment]
Hello again @Kegs2477 ,
As promised I've updated the ReadMe of the project to be more explicit on how to use this and broken down the commandline parameters explaining what they mean and how to use them.  I'll also make sure this still works as intended later this evening to make sure it's not just broken in the first place.  I'll report back; it'll be in about 10 hours I expect.

**Comment by agearhart** [comment]
@Kegs2477 I lied and was able to test.  It appears to be working as expected.  After running I had both cards.pdf and printable.pdf in my C:\Temp folder.  I'll keep this issue open until you've had a chance to try and report back with either success or if you need more help.  :)

**Comment by Kegs2477** [comment]
Thank you for the reply :) I will try this now and return with results

**Comment by Kegs2477** [comment]
I assume I run the command in CMD (I'm on windows and Docker is installed), but I get the result: " image operating system "linux" cannot be used on this platform."

**Comment by agearhart** [comment]
Your assumption is correct.  You may to switch to Linux Containers in Docker:
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

Docker on Windows should be able to run Linux containers.  Alternatively you could try this command:
```
docker run -it --platform linux -v c:/temp:/opt/output pnzrdrgoon/dndspelldeck:latest
```
Examples of running Linux containers on Windows can be found here, https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10-linux

**Comment by Kegs2477** [comment]
I get various errors depending on what I try. So If i switch to Linux containers, which command do I use? I have turned experimental features on as the command you supplied above, said it required it but didn't work even after I turned it on. Not sure what I'm doing wrong

**Comment by agearhart** [comment]
If you switch to Linux containers you should be able to use the default command:
```
docker run -it -v c:/temp:/opt/output pnzrdrgoon/dndspelldeck:latest
```
Could you post some of the errors you're seeing?  Maybe I can help figure out what they mean.

**Comment by Kegs2477** [comment]
Doing it with linux container and the above command, I receive this error:
```
"docker: Error response from daemon: status code not OK but 500: {"Message":"Unhandled exception: Drive has not been shared"}.
See 'docker run --help'."
```

**Comment by agearhart** [comment]
Fantastic!  Looks like you may need to just share your C:\ drive with Docker.  Directions on how to do that can be found here,
https://docs.microsoft.com/en-gb/archive/blogs/stevelasker/configuring-docker-for-windows-volumes

**Comment by agearhart** [comment]
![image](https://user-images.githubusercontent.com/2504116/76079259-2fd13c80-5f9c-11ea-9518-621862da916e.png)

**Comment by Kegs2477** [comment]
Great! That seemed to work, it's currently downloading, I'll follow up once complete.

**Comment by Kegs2477** [comment]
Worked perfectly, Thank you sou much for the support and patience. Really appreciate it!

**Comment by agearhart** [comment]
Good luck with the campaign!
